 export const CHANGE_LOGGING_BUTTON ="CHANGE_LOGGING_BUTTON";
 export const CHANGE_SIGNUP_LOGIN = "CHANGE_SIGNUP_LOGIN";
 export const CHANGE_LOGGEDIN ="CHANGE_LOGGEDIN";
 export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD"; 
